<?php

namespace Sistemadmin\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CajaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CajaRepository extends EntityRepository
{
	public function Create($caja) 
	{
	    $em = $this->getEntityManager();	
	    $em->persist($caja);
	    $em->flush();
		return true;
	}

	public function Update($caja, $cantidad) 
	{
		$caja->setCantidad($cantidad);

	    $em = $this->getEntityManager();	
	    $em->persist($caja);
	    $em->flush();
		return true;
	}

	public function getCajaPorFecha($fecha) 
	{
       $em = $this->getEntityManager();
       $dql = "SELECT v FROM BackendBundle:Caja v
          where v.fechacuadre=:fecha";
        $consulta = $em->createQuery($dql)            
            ->setParameter('fecha', date_format($fecha, 'Y-m-d'));
        return $consulta->getResult();
    }
}
