<?php

namespace Sistemadmin\BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoArticuloRepository extends EntityRepository
{
 /**
    public function findBuscadorArticulos($fechainicio,$fechafinal,$marca,$nombre) {

        $query= $this-> queryBuscadorArticulos($fechainicio,$fechafinal,$marca,$nombre);
        $prueba = $query->getResult();

        return $prueba;

    }

    public function queryBuscadorArticulos($fechainicio,$fechafinal,$marca,$nombre) {

        $qb = $this->createQueryBuilder('c');
        $qb->add('select', 'c')
            ->add('where', '2 = :siempre')
            ->setParameter('siempre', '2');


        if ($fechainicio!="Todos") {
            $qb ->andWhere( 'c.fechacompra > :fechainicio')
                ->setParameter('fechainicio', $fechainicio);

        }
        if ($fechafinal!="Todos") {
            $qb ->andWhere( 'c.fechacompra < :fechafinal')
                ->setParameter('fechafinal', $fechafinal);

        }
        if ($marca!="Todos") {
            $qb ->andWhere( 'c.marca = :marca')
                ->setParameter('marca', $marca);

        }

        if ($nombre!="Todos") {
            $qb ->andWhere( 'c.nombre = :nombre')
                ->setParameter('nombre', $nombre);

        }

        $query = $qb->getQuery();
        return $query;
    }

    public function queryTodosLosArticulosporNombre($nombre, $limit, $offset) {
        $em = $this->getEntityManager();


        $consulta = $em->createQuery('SELECT c FROM BackendBundle:Articulo c WHERE p.nombre LIKE :nombre');
        $consulta->setParameter('nombre', '%' . $nombre . '%');



        $consulta->setMaxResults($limit);
        $consulta->setFirstResult($offset);
        return $consulta;
    }

    public function findTodosLosArticulosporNombre($nombre,$limit,$offset) {
        return $this->queryTodosLosArticulosporNombre($nombre,$limit,$offset)->getResult();
    }
  *  */
}
