services:
#    inventario.example:
#        class: InventarioBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    inventario.services:
        class: InventarioBundle\Services\InventarioService
        arguments: [@doctrine.orm.entity_manager,@service_container]
